--LTER TABLE yh ADD CONSTRAINT ogr PRIMARY KEY (pole1);
--ALTER TABLE yn ADD CONSTRAINT ogr1 PRIMARY KEY (pole3);

--ALTER TABLE yn ADD CONSTRAINT ogr1 PRIMARY KEY (pole3);
--ALTER TABLE yn ADD CONSTRAINT ogr1 PRIMARY KEY (pole3);
--ALTER TABLE yn ADD CONSTRAINT ogr1 PRIMARY KEY (pole3);
--ALTER TABLE yn ADD CONSTRAINT ogr1 PRIMARY KEY (pole3);
--ALTER TABLE yn ADD CONSTRAINT ogr1 PRIMARY KEY (pole3);
ALTER TABLE installs ADD CONSTRAINT ins_soft FOREIGN KEY (soft_id) REFERENCES soft (id);
ALTER TABLE installs ADD CONSTRAINT ins_pcs FOREIGN KEY (pc_id) REFERENCES pcs (id);
ALTER TABLE pcs ADD CONSTRAINT pcs_rooms FOREIGN KEY (room_id) REFERENCES rooms (id);
ALTER TABLE rooms ADD CONSTRAINT rooms_employees FOREIGN KEY (emp_id) REFERENCES employees (id);



