DROP TABLE IF EXISTS installs;
DROP TABLE IF EXISTS soft;
DROP TABLE IF EXISTS pcs;
DROP TABLE IF EXISTS rooms;
DROP TABLE IF EXISTS employees;

CREATE TABLE installs 
(pc_id INTEGER , soft_id INTEGER,  PRIMARY KEY(pc_id, soft_id));

CREATE TABLE soft 
(id INTEGER PRIMARY KEY, sname CHAR(50), ver INTEGER, quant INTEGER DEFAULT 0);

CREATE TABLE pcs 
(id INTEGER PRIMARY KEY, room_id INTEGER, note CHAR(50), ip_addr CHAR(15), mac_addr CHAR(17));

CREATE TABLE rooms 
(id INTEGER PRIMARY KEY, num INTEGER GENERATED ALWAYS AS IDENTITY, emp_id INTEGER);

CREATE TABLE employees 
(id INTEGER PRIMARY KEY, lname CHAR(50), fname CHAR(50), mname CHAR(50));
